<?php

function ctsearch_theme($existing, $type, $theme, $path) {
  return array(
    'facet_block' => array(
      'variables' => array('facet_id' => NULL, 'facet' => NULL),
    ),
    'sort_block' => array(
      'variables' => array('sortable' => array()),
    ),
    'ctsearch_result_item' =>  array(
      'variables' => array('item' => NULL),
    ),
    'ctsearch_result_list' =>  array(
      'variables' => array('items' => NULL, 'total' => NULL),
    ),
  );
}

function ctsearch_entity_insert(Drupal\Core\Entity\EntityInterface $entity){
  \Drupal\ctsearch\Controller\ExportController::handleEntityUpdate($entity);
}

function ctsearch_entity_update(Drupal\Core\Entity\EntityInterface $entity){
  \Drupal\ctsearch\Controller\ExportController::handleEntityUpdate($entity);
}

function ctsearch_entity_delete(Drupal\Core\Entity\EntityInterface $entity){
  \Drupal\ctsearch\Controller\ExportController::handleEntityDelete($entity);
}