<?php

function ctsearch_theme($existing, $type, $theme, $path) {
  return array(
    'facet_block' => array(
      'variables' => array('facet_id' => NULL, 'facet' => NULL),
    ),
    'ctsearch_result_item' =>  array(
      'variables' => array('item' => NULL),
    ),
    'ctsearch_result_list' =>  array(
      'variables' => array('items' => NULL, 'total' => NULL),
    ),
  );
}

function ctsearch_node_insert(Drupal\Core\Entity\EntityInterface $entity){
  \Drupal\ctsearch\Controller\ExportController::handleNodeUpdate($entity);
}

function ctsearch_node_update(Drupal\Core\Entity\EntityInterface $entity){
  \Drupal\ctsearch\Controller\ExportController::handleNodeUpdate($entity);
}

function ctsearch_node_delete(Drupal\Core\Entity\EntityInterface $entity){
  \Drupal\ctsearch\Controller\ExportController::handleNodeDelete($entity);
}